var ugChat = {
  'view.chat': 'سۆھبەت',
  'number.groupSeparator': ',',
  'duration.compactSeconds': '{seconds} سېكۇنت',
  'duration.compactMinutes': '{minutes} مىنۇت {seconds} سېكۇنت',
  'duration.milliseconds': '{milliseconds} مىللىسېكۇنت',
  'stats.counts': '{turns} نۆۋەت {steps} قەدەم',
  'stats.cacheHit': 'غەملەك ئۇرۇشى {percent}%',
  'stats.dialog.title': 'سېئانس ستاتىستىكىسى',
  'stats.dialog.usageTitle': 'توكېن ئىشلىتىلىشى',
  'stats.dialog.llmTime': 'مودېل ۋاقتى',
  'stats.dialog.toolTime': 'قورال چاقىرىش ۋاقتى',
  'stats.dialog.ttft': 'تۇنجى توكېن ئوتتۇرىچە ۋاقتى (TTFT)',
  'stats.dialog.speed': 'چىقىرىش سۈرئىتى (TPS)',
  'chat.loadingHistory': 'تارىخ يۈكلىنىۋاتىدۇ…',
  'chat.loadError': 'تارىخنى يۈكلەش مەغلۇپ بولدى: {message} ({code})',
  'chat.loadOlder': 'تېخىمۇ بۇرۇنقىنى يۈكلەش',
  'chat.toBottom': 'ئاستىغا قايتىش',
  'chat.deepDiving': 'چوڭقۇر ئىزدىنىۋاتىدۇ...',
  'chat.turnNavigation.label': 'نۆۋەت يۆتكىلىشى',
  'chat.turnNavigation.jump': '{turn}-نۆۋەتكە ئاتلاش',
  'chat.turnNavigation.jumpLoad': 'يۈكلەپ {turn}-نۆۋەتكە ئاتلاش',
  'chat.turnNavigation.turn': '{turn}-نۆۋەت',
  'settings.transcript.title': 'سۆھبەت كۆرۈنۈشى',
  'settings.transcript.description': 'تاماملانغان نۆۋەتلەردىكى جەريان مەزمۇنىنى كونترول قىلىدۇ',
  'settings.transcript.normal': 'ئۆلچەملىك',
  'settings.transcript.compact': 'ئىخچام',
  'fileOpen.title': 'ھۆججەتنى ئاچقىلى بولمىدى',
  'fileOpen.unknown': 'بۇ ھۆججەتنى ئاچقىلى بولمىدى',
  'message.extraBlock': 'قوشۇمچە مەزمۇن بۆلىكى',
  'message.systemPrompt': 'سىستېما كۆرسەتمىسى',
  'message.systemPromptUpdate': 'سىستېما كۆرسەتمىسى يېڭىلاندى',
  'message.contextInjection': 'كونتېكىست قىستۇرۇش',
  'message.contextRecall': 'سېئانس ئارا ئەسلىيەلەش',
  'message.referenceSummary': 'نەقىل سېئانسى · {labels}',
  'message.referenceSeparator': '،',
  'message.context.instructions.loaded': 'يۈكلەندى',
  'message.context.instructions.added': 'قوشۇلدى',
  'message.context.instructions.updated': 'يېڭىلاندى',
  'message.context.instructions.removed': 'چىقىرىۋېتىلدى',
  'message.context.catalog.replaced': 'ئالماشتۇرۇش مۇندەرىجىسى',
  'message.context.catalog.more': '… يەنە {count} تال بار',
  'message.context.snapshot.supersedes': 'ئالدىنقى كۆرۈنۈشلەرنىڭ ئورنىنى ئالىدۇ',
  'message.context.relay.from': '{session} سېئانسىدىن كەلدى',
  'message.context.recall.counts': '{retained} تال ساقلاندى · {omitted} تال قالدۇرۇلدى',
  'message.context.recall.truncated': 'قىسقارتىلدى',
  'message.compaction': 'كونتېكىست قىسىلدى',
  'message.compaction.running': 'قىسىلىۋاتىدۇ…',
  'message.compaction.completed': '{items} تال تارىخىي خاتىرە قىسىلدى (تەخمىنەن {tokens} توكېن)',
  'message.compaction.expand': 'قىسىش خۇلاسىسىنى كۆرۈش',
  'message.compaction.unavailable': 'قىسىش خۇلاسىسىنى ئىشلەتكىلى بولمايدۇ',
  'message.compaction.commandTitle': 'compact',
  'message.think': 'ئويلىنىش',
  'message.unknownSurface': 'نامەلۇم surface ۋەقەسى: {type}',
  'message.unknownBlock': 'نامەلۇم مەزمۇن بۆلىكى',
  'message.turnProcess.toolCalls.one': '{count} قېتىم قورال چاقىرىش',
  'message.turnProcess.toolCalls.other': '{count} قېتىم قورال چاقىرىش',
  'message.turnProcess.messages.one': '{count} تال ئۇچۇر',
  'message.turnProcess.messages.other': '{count} تال ئۇچۇر',
  'message.turnProcess.subagents.one': '{count} تارماق ۋاكالەتچى',
  'message.turnProcess.subagents.other': '{count} تارماق ۋاكالەتچى',
  'message.turnProcess.thoughtForAWhile': 'ئويلىنىپ بولدى',
  'message.turnProcess.separator': ' · ',
  'message.stopped': 'توختىتىلدى',
  'message.branch': 'يېڭى سۆھبەتكە شاخلىنىش',
  'message.branchUnavailable': 'پەقەت تاماملانغان نۆۋەتنىڭ ئەڭ ئاخىرقى ئۇچۇرىدىن شاخلىنىشقا بولىدۇ',
  'message.retry.active': 'مودېل تەلىپىنى قايتا سىنىۋاتىدۇ',
  'message.retry.cancelled': 'مودېل تەلىپىنى قايتا سىناش بىكار قىلىندى',
  'message.retry.started': 'مودېل تەلىپى قايتا سىنالدى',
  'message.retry.scheduled': 'مودېل تەلىپىنى قايتا سىناشنى كۈتۈۋاتىدۇ',
  'message.retry.status': '{label} ({retry}/{maximum}) · {seconds}s',
  'message.retry.delay': 'قايتا سىناش كېچىكتۈرۈلۈشى: ',
  'message.retry.failure': 'مەغلۇبىيەت سەۋەبى: ',
  'message.failure.auth': 'API ئاچقۇچى ئىناۋەتسىز',
  'message.turnError': 'بۇ نۆۋەت مەغلۇپ بولدى',
  'message.maxTokens': 'چىقىرىش توكېن چېكىگە يەتتى',
  'message.maxTokens.hint': 'جاۋاب قىسقارتىلدى، ئالدىنقى چىقىرىش سۆھبەتتە ساقلاندى. «داۋاملاشتۇر» دەپ ئەۋەتسىڭىز مودېل داۋام قىلالايدۇ.',
  'message.ranFor': '{duration} ۋاقىت سەرپ قىلىندى',
  'message.tokensPerSecond': '{tps} tok/s',
  'message.turnUsage.title': 'بۇ نۆۋەتنىڭ ئىشلىتىلىشى',
  'message.turnUsage.consumed': 'ئىشلىتىش {total}',
  'message.turnUsage.model': 'تەمىنلىگۈچى / مودېل',
  'message.turnUsage.cacheHit': 'غەملەك ئۇرۇشى',
  'message.turnUsage.input': 'غەملەكلەنمىگەن كىرگۈزۈش',
  'message.turnUsage.cacheRead': 'غەملەكتىن ئوقۇش',
  'message.turnUsage.cacheWrite': 'غەملەككە يېزىش',
  'message.turnUsage.output': 'چىقىرىش',
  'message.turnUsage.reasoning': ' (ئىچىدە {tokens} خۇلاسە چىقىرىش)',
  'message.turnUsage.count': '{count} tok',
  'message.turnTime.title': 'بۇ نۆۋەتنىڭ ۋاقتى ۋە سۈرئىتى',
  'message.turnTime.duration': 'بۇ نۆۋەتنىڭ ئومۇمىي ۋاقتى',
  'message.turnTime.speed': 'چىقىرىش سۈرئىتى (TPS)',
  'message.turnTime.ttft': 'تۇنجى توكېن ۋاقتى (TTFT)',
  'duration.seconds': '{seconds} سېكۇنت',
  'duration.minutes': '{minutes} مىنۇت {seconds} سېكۇنت',
  'command.running': 'ئىجرا بولۇۋاتىدۇ…',
  'command.failed': 'بۇيرۇق مەغلۇپ بولدى',
  'command.done': 'تاماملاندى',
  'command.title': 'بۇيرۇق',
  'row.running': 'ئىجرا بولۇۋاتىدۇ',
  'row.failed': 'مەغلۇپ بولدى',
  'json.truncated': '… قىسقارتىلدى، جەمئىي {total} بەلگە',
  'clock.md': '{m}-ئاي {d}-كۈن',
  'clock.ymd': '{y}-يىل {m}-ئاي {d}-كۈن',
}
