var ugCommon = {
  'ok': 'ماقۇل',
  'cancel': 'بىكار قىلىش',
  'close': 'يېپىش',
  'copy': 'كۆچۈرۈش',
  'copied': 'كۆچۈرۈلدى',
  'copy.failed': 'كۆچۈرۈش مەغلۇپ بولدى',
  'copy.value': 'قىممەتنى كۆچۈرۈش',
  'copy.json': 'JSON نى كۆچۈرۈش',
  'copy.path': 'خاسلىق يولىنى كۆچۈرۈش',
  'copy.prettyJson': 'فورماتلانغان JSON نى كۆچۈرۈش',
  'copy.compactJson': 'ئىخچام JSON نى كۆچۈرۈش',
  'copy.optionsHint': '{action}؛ ئوڭ كۇنۇپكا بىلەن چېكىپ كۆچۈرۈش ئۇسۇلىنى تاللىغىلى بولىدۇ',
  'retry': 'قايتا سىناش',
  'loading': 'يۈكلىنىۋاتىدۇ…',
  'load.failed': 'يۈكلەش مەغلۇپ بولدى',
  'submit': 'تاپشۇرۇش',
  'submitting': 'تاپشۇرۇلۇۋاتىدۇ…',
  'next': 'كېيىنكى قەدەم',
  'previous': 'ئالدىنقى قەدەم',
  'skip': 'ئاتلاپ ئۆتۈش',
  'delete': 'ئۆچۈرۈش',
  'edit': 'تەھرىرلەش',
  'save': 'ساقلاش',
  'search': 'ئىزدەش',
  'more': 'تېخىمۇ كۆپ',
  'collapse': 'قاتلاش',
  'expand': 'يېيىش',
  'back': 'قايتىش',
  'brand.localBuild': 'DSH يەرلىك قۇرۇلمىسى',
  'unknown': 'نامەلۇم',
  'none': 'يوق',
  'truncated': 'قىسقارتىلدى',
  'json.collapseNode': 'JSON تۈگۈنىنى قاتلاش',
  'json.expandNode': 'JSON تۈگۈنىنى يېيىش',
  'json.label': 'JSON',
  'markdown.footnotes': 'ئاستى خاتىرە',
  'markdown.truncatedCharacters': '… قىسقارتىلدى، جەمئىي {total} بەلگە',
  'number.thousand': '{value}K',
  'number.million': '{value}M',
}
