var ugCommand = {
  'description.compact': 'يۇقىرىقى سۆھبەت مەزمۇنىنى قىسىش',
  'description.export': 'بۇ سېئانسنىڭ مەزمۇنىنى ZIP قىلىپ ئېكسپورت قىلىش',
  'description.feedback': 'بۇ سېئانس ھەققىدە پىكىر يوللاش',
  'description.goal': 'ئۇزۇن مۇددەتلىك ۋەزىپىنىڭ نىشانىنى بەلگىلەش ياكى كۆرۈش',
  'description.permission': 'ھوقۇق ئالدىن سەپلىمىسىنى ئالماشتۇرۇش (قۇم ساندۇقى ھالىتى ۋە تەستىقلاش سىياسىتى)',
  'description.plan': 'پىلان ھالىتىگە كىرىش ياكى چىقىش',
  'search.placeholder': 'ئىزدەش…',
  'search.aria': 'تاللانمىلارنى سۈزۈش',
  'status.loading': 'تاللانمىلار يۈكلىنىۋاتىدۇ…',
  'status.applying': 'قوللىنىلىۋاتىدۇ…',
  'status.empty': 'تاللانما يوق',
  'overlay.aria': '/{command} تاللانمىلىرى',
  'listbox.aria': '/{command} ماس كەلگەنلەر',
  'notice.attachmentsUnsupported': '/{command} قوشۇمچىنى قوبۇل قىلمايدۇ؛ ئاۋۋال قوشۇمچىنى چىقىرىۋېتىڭ',
}
