var ugConversation = {
  'hint.plan': 'پىلان ھاسىل قىلىش ئۈچۈن ۋەزىپىڭىزنى تەسۋىرلەڭ',
  'hint.goal': 'ئۇزۇن مۇددەتلىك ۋەزىپىنىڭ نىشانىنى تەسۋىرلەڭ',
  'hint.goal.active': 'نىشان ئاكتىپ — edit تەھرىرلەش / pause ۋاقىتلىق توختىتىش / resume داۋاملاشتۇرۇش / clear تازىلاش',
  'placeholder.plan': 'پىلان ھاسىل قىلىش ئۈچۈن ۋەزىپىڭىزنى تەسۋىرلەڭ',
  'placeholder.default': 'ئۇچۇر ئەۋەتىڭ ياكى ۋەزىپە ئىجرا قىلىڭ، / بۇيرۇقلار، @ ھۆججەت ياكى سېئانسلار',
  'placeholder.unavailable': 'سېئانسنى ئىشلەتكىلى بولمايدۇ',
  'placeholder.parentOffline': 'ئانا سېئانس تورسىز ھالەتتە؛ ئەۋەتىشكە بولمايدۇ، ئەمما يۈرگۈزۈشنى توختىتالايسىز',
  'placeholder.hero': 'قۇرماقچى بولغان نەرسىڭىزنى تەسۋىرلەڭ، / بۇيرۇقلار، @ ھۆججەت ياكى سېئانسلار',
  'placeholder.workspace': 'باشلاش ئۈچۈن خىزمەت بوشلۇقىنى تاللاڭ',
  'placeholder.steerQueue': 'Cmd/Ctrl+Enter ئۆچرەتتىكى بارلىق ئۇچۇرلارنى ئارىغا ئەۋەتىدۇ',
  'input.commands': 'بۇيرۇقلار',
  'input.stop': 'ھاسىل قىلىشنى توختىتىش',
  'input.send': 'ئۇچۇر ئەۋەتىش',
  'input.send.queue': 'ئۆچرەتكە قويۇش',
  'input.send.steer': 'ئارىغا ئەۋەتىش',
  'input.accessMode': 'زىيارەت ھالىتى، ھازىرقى: {name}',
  'attachment.pending': 'ئەۋەتىلىدىغان قوشۇمچىلار',
  'attachment.scrollLeft': 'قوشۇمچىلارنى سولغا سۈرۈش',
  'attachment.scrollRight': 'قوشۇمچىلارنى ئوڭغا سۈرۈش',
  'attachment.dropTitle': 'ھۆججەت ياكى سۈرەتلەرنى بۇ يەرگە سۆرەپ قوشۇڭ',
  'attachment.dropDesc': 'سۈرەت چېكى: ئەڭ كۆپ {count} دانە، ھەر بىرى {size}',
  'attachment.dropBlocked': 'ھازىرچە ھۆججەت ياكى سۈرەت قوشقىلى بولمايدۇ',
  'image.pending': 'ئەۋەتىلىدىغان سۈرەتلەر',
  'image.openOriginal': 'ئەسلى سۈرەتنى كۆرۈش',
  'image.openOriginalLabel': '{label}، ئەسلى سۈرەتنى كۆرۈش ئۈچۈن چېكىڭ',
  'image.remove': '{name} سۈرىتىنى چىقىرىۋېتىش',
  'image.original': 'ئەسلى سۈرەت',
  'image.label': 'سۈرەت',
  'image.loadFailed': 'سۈرەت يۈكلەش مەغلۇپ بولدى؛ قايتا سىناش ئۈچۈن چېكىڭ',
  'image.loading': 'سۈرەت يۈكلىنىۋاتىدۇ…',
  'image.preview': 'ئەسلى سۈرەتنى ئالدىن كۆرۈش',
  'image.closePreview': 'ئەسلى سۈرەت ئالدىن كۆرۈشنى يېپىش',
  'image.unsupportedType': 'پەقەت PNG، JPG، WebP، GIF فورماتىدىكى سۈرەتلەرلا قوللىنىلىدۇ',
  'image.tooMany': 'بىر ئۇچۇرغا ئەڭ كۆپ {count} سۈرەت قوشقىلى بولىدۇ',
  'image.fileTooLarge': 'ھەر بىر سۈرەت {size} دىن كىچىك بولۇشى كېرەك',
  'image.totalTooLarge': 'سۈرەتلەرنىڭ ئومۇمىي چوڭلۇقى {size} دىن ئېشىپ كەتتى؛ بەزى سۈرەتلەرنى چىقىرىۋېتىپ قايتا سىناڭ',
  'image.tooManyPixels': 'سۈرەتنىڭ ئېنىقلىقى بەك يۇقىرى؛ قىسىپ قايتا سىناڭ',
  'image.dimensionTooLarge': 'سۈرەتنىڭ كەڭلىك-ئېگىزلىكى ئەڭ كۆپ {size}px بولۇشى كېرەك؛ كىچىكلىتىپ قايتا سىناڭ',
  'image.modelUnsupported': 'ھازىرقى مودېل سۈرەتنى قوللىمايدۇ؛ سۈرەتنى قوللايدىغان مودېلغا ئالماشتۇرۇڭ',
  'image.sendFailed': 'سۈرەت ئەۋەتىش مەغلۇپ بولدى ({reason})؛ سۈرەتلەرنى قايتا قوشۇپ سىناڭ',
  'file.attach': 'قوشۇمچە قوشۇش',
  'file.pending': 'ئەۋەتىلىدىغان ھۆججەتلەر',
  'file.remove': '{name} ھۆججىتىنى چىقىرىۋېتىش',
  'file.uploading': 'يۈكلىنىۋاتىدۇ…',
  'file.uploadFailed': 'يۈكلەش مەغلۇپ بولدى؛ قايتا سىناش ئۈچۈن چېكىڭ',
  'file.retry': '{name} نى قايتا يۈكلەش',
  'file.stillUploading': 'ھۆججەتلەر تېخى يۈكلىنىۋاتىدۇ؛ يۈكلەش تاماملانغاندىن كېيىن ئەۋەتىڭ',
  'file.sessionUnavailable': 'سېئانسنى ئىشلەتكىلى بولمايدۇ؛ ھۆججەت يۈكلىگىلى بولمايدۇ',
  'file.notStaged': 'ھۆججەت تېخى يۈكلىنىپ بولمىدى؛ قايتا قوشۇپ سىناڭ',
  'file.label': 'ھۆججەت',
  'context.aria': 'كونتېكىستنىڭ {percent} ى ئىشلىتىلدى',
  'context.used': 'كونتېكىست ئىشلىتىلدى',
  'context.system': 'سىستېما كۆرسەتمىسى',
  'context.tools': 'قورال ئېنىقلىمىلىرى',
  'context.messages': 'سۆھبەت ئۇچۇرلىرى',
  'settings.enter.title': 'ئالدىراش چاغدىكى ئەۋەتىش ھەرىكىتى',
  'settings.enter.description': 'ۋاكالەتچى ئىجرا بولۇۋاتقاندا Enter ۋە ئەۋەتىش كۇنۇپكىسىنىڭ ھەرىكىتى؛ Cmd/Ctrl+Enter باشقا ھەرىكەتنى ئىشلىتىدۇ',
  'settings.enter.queue': 'ئۆچرەتكە قويۇش',
  'settings.enter.steer': 'ئارىغا ئەۋەتىش',
  'access.preset.readOnly': 'پەقەت ئوقۇش',
  'access.preset.workspaceWrite': 'خىزمەت بوشلۇقىدا ئۆزگەرتىش',
  'access.preset.fullAccess': 'تولۇق ھوقۇق',
  'access.confirm.title': 'تولۇق ھوقۇقنى قوزغىتامسىز؟',
  'access.confirm.description': 'تولۇق ھوقۇق قوزغىتىلسا، ۋاكالەتچى تەستىقلاش قەدەملىرىنى ئازايتىپ، سەزگۈر مەشغۇلاتلار، ھۆججەت ئۆزگەرتىش ياكى سىرتقى بۇيرۇقلارنى ئۆز ئىچىگە ئالغان تېخىمۇ كۆپ مەشغۇلاتنى بىۋاسىتە ئىجرا قىلالايدۇ. پەقەت ھازىرقى ۋەزىپىگە ئىشەنگەندىلا ئىشلىتىڭ.',
  'access.confirm.acknowledge': 'خەۋپنى چۈشەندىم، داۋاملاشتۇرۇشقا رازى',
  'access.confirm.cancel': 'بىكار قىلىش',
  'access.confirm.enable': 'تولۇق ھوقۇقنى قوزغىتىش',
  'hero.headline': 'نامەلۇم دۇنياغا سەپەر',
  'hero.preview': 'ئالدىن كۆرۈش نۇسخىسى',
  'hero.chooseWorkspace': 'خىزمەت بوشلۇقىنى تاللاش',
  'session.hierarchy': 'سېئانس قاتلىمى',
  'todo.title': 'ۋەزىپە تىزىمى',
  'todo.progress.done': '{done} تاماملاندى',
  'todo.progress.active': '{active} داۋاملاشماقتا',
  'todo.progress.pending': '{pending} ساقلىنىۋاتىدۇ',
  'todo.rowTitle': 'ۋەزىپە تىزىمىنى يېڭىلاش',
  'todo.completed': '{done}/{total} تاماملاندى',
  'command.attachmentsUnsupported': '/{command} قوشۇمچىنى قوبۇل قىلمايدۇ؛ ئاۋۋال قوشۇمچىنى چىقىرىۋېتىڭ',
  'ask.rowTitle': 'سوئال سوراش',
  'ask.waiting': 'جاۋاب كۈتۈلۈۋاتىدۇ',
  'ask.cancelled': 'بىكار قىلىندى',
  'ask.cancelledDetail': 'بۇ سوئال توپلىمى جاۋاب يوللانمىسىن بىكار قىلىندى.',
  'ask.interrupted': 'ئۈزۈلدى',
  'ask.interruptedDetail': 'بۇ سوئال توپلىمى جاۋاب يوللانمىسىن ئۈزۈلۈپ قالدى.',
  'ask.answered': '{answered}/{total} جاۋاب بېرىلدى',
  'ask.skipped': 'جاۋاب بېرىلمىدى',
  'bash.running': 'ئىجرا بولۇۋاتىدۇ',
  'bash.failed': 'مەغلۇپ بولدى',
  'bash.stopped': 'توختىتىلدى',
  'row.running': 'ئىجرا بولۇۋاتىدۇ',
  'row.failed': 'مەغلۇپ بولدى',
  'row.stopped': 'توختىتىلدى',
  'row.input': 'كىرگۈزۈش',
  'row.output': 'چىقىرىش',
  'row.inspect': 'كۆرۈش',
  'tool.title.search': 'ئىزدەش',
  'tool.title.read': 'ئوقۇش',
  'tool.title.bash': 'Bash',
  'tool.title.write': 'يېزىش',
  'tool.title.edit': 'تەھرىرلەش',
  'tool.title.code': 'كود',
  'tool.title.generic': 'قورال چاقىرىش',
  'tool.title.inspect': 'كۆرۈش',
  'tool.title.runCordis': 'Cordis قىستۇرمىسىنى ئىجرا قىلىش',
  'tool.title.stopCordis': 'Cordis قىستۇرمىسىنى توختىتىش',
  'tool.title.removeCordis': 'Cordis قىستۇرمىسىنى چىقىرىۋېتىش',
  'tool.title.pwsh': 'Pwsh',
  'tool.title.readImage': 'سۈرەت ئوقۇش',
  'tool.title.grep': 'Grep',
  'tool.title.glob': 'Glob',
  'tool.title.webSearch': 'تور ئىزدەش',
  'tool.title.webFetch': 'تور بەت ئېلىش',
  'diff.files.one': '{count} ھۆججەت',
  'diff.files.other': '{count} ھۆججەت',
  'diff.collapseAria': 'پەرقنى قاتلاش',
  'diff.expandAria': 'قالغان {count} قۇر پەرقنى يېيىش',
  'diff.expandRest': '… قالغان {count} قۇر',
  'read.window': '{shown} / {total} قۇر كۆرسىتىلدى',
  'read.collapseAria': 'مەزمۇننى قاتلاش',
  'read.expandAria': 'قالغان {count} قۇرنى يېيىش',
  'read.expandRest': '… قالغان {count} قۇر',
  'search.paths': '{shown} يول',
  'search.paths.truncated': '{shown} / جەمئىي {total} يول كۆرسىتىلدى',
  'search.matches': '{shown} جاي ماس كەلدى · {files} ھۆججەت',
  'search.matches.truncated': '{shown} / جەمئىي {total} جاي ماس كەلدى · {files} ھۆججەت',
  'search.noResults': 'نەتىجە يوق',
  'search.collapseAria': 'نەتىجىلەرنى قاتلاش',
  'search.expandAria': 'قالغان {count} قۇر نەتىجىنى يېيىش',
  'search.expandRest': '… قالغان {count} قۇر',
  'web.noResults': 'نەتىجە تېپىلمىدى',
  'web.sourcesTruncated': 'مەنبە تىزىملىكى قىسقارتىلدى',
  'web.http': 'HTTP',
  'web.contentTruncated': 'مەزمۇن قىسقارتىلدى',
  'details.running': 'ئىجرا بولۇۋاتىدۇ…',
  'queue.count': '{n} ئۆچرەتتىكى ئۇچۇر',
  'queue.sending': 'ئەۋەتىلىۋاتىدۇ…',
  'queue.image': 'ئۆچرەتتىكى ئۇچۇر سۈرىتى',
  'queue.file': 'ئۆچرەتتىكى ھۆججەت {name}',
  'queue.edit': 'ئۆچرەتتىكى ئۇچۇرنى تەھرىرلەش',
  'queue.edit.unsupported': 'تېكىستسىز مەزمۇن بار؛ تەھرىرلەشنى تېخى قوللىمايدۇ',
  'queue.save': 'ئۆچرەتتىكى ئۇچۇرنى ساقلاش',
  'queue.cancelEdit': 'تەھرىرلەشنى بىكار قىلىش',
  'queue.remove': 'ئۆچرەتتىكى ئۇچۇرنى ئۆچۈرۈش',
  'queue.steer': 'ئارىغا ئەۋەتىش',
  'queue.steer.unavailable': 'پەقەت ۋاكالەتچى ئىجرا بولۇۋاتقاندا ئارىغا ئەۋەتكىلى بولىدۇ',
  'queue.editFailed': 'تەھرىرلەش مەغلۇپ بولدى: بۇ ئۇچۇر ئەۋەتىلىشكە باشلىغان بولۇشى مۇمكىن.',
  'queue.removeFailed': 'ئۆچۈرۈش مەغلۇپ بولدى: بۇ ئۇچۇر ئەۋەتىلىشكە باشلىغان بولۇشى مۇمكىن.',
  'queue.steerFailed': 'ئارىغا ئەۋەتىش مەغلۇپ بولدى. قايتا سىناڭ.',
  'terminal.signal': 'سىگنال {signal}',
  'terminal.exitCode': 'چىقىش كودى {code}',
  'terminal.running': 'ئىجرا بولۇۋاتىدۇ',
  'terminal.failed': 'مەغلۇپ بولدى',
  'terminal.done': 'تاماملاندى',
  'terminal.noOutput': 'چىقىرىش يوق',
  'terminal.collapseAria': 'چىقىرىشنى قاتلاش',
  'terminal.expandAria': 'قالغان {n} قۇر چىقىرىشنى يېيىش',
  'terminal.expandRest': '… قالغان {n} قۇر',
  'terminal.sendInput': '(كىرگۈزۈشنى ئەۋەتىش)',
  'terminal.session': 'تېرمىنال {sessionId}',
}
