var ugCordis = {
  'row.defineTitle': 'Cordis قىستۇرمىسىنى تىزىملاش',
  'row.runTitle': 'Cordis قىستۇرمىسىنى يۈرگۈزۈش',
  'row.updateTitle': 'Cordis قىستۇرمىسىنى يېڭىلاش',
  'row.stopTitle': 'Cordis قىستۇرمىسىنى توختىتىش',
  'row.removeTitle': 'Cordis قىستۇرمىسىنى چىقىرىۋېتىش',
  'purpose.missing': '(ئىشلىتىش مەقسىتى يېزىلمىغان)',
  'status.idle': 'تەييار',
  'status.awaitingApproval': 'تەستىقنى كۈتۈۋاتىدۇ',
  'status.failed': 'يۈرگۈزۈش مەغلۇپ بولدى',
  'status.clientPending': 'Client تەييار',
  'status.running': 'ئىجرا بولۇۋاتىدۇ',
  'status.removed': 'چىقىرىۋېتىلدى',
  'status.superseded': 'يېڭىراق ئىجرا بار',
  'run.removed': 'بۇ بوغچا ئەمدى مەۋجۇت ئەمەس',
  'run.superseded': 'يېڭىراق ئىجرا كارتىسى تۆۋەندە بار',
  'panel.hint': 'يۈرگۈزۈش كونتروللىرى سول ئاستىدىكى تەڭشەك ئۈستىدىكى Cordis تاختىسىدا',
  'panel.plugins.aria': 'Cordis قىستۇرمىلىرى',
  'panel.approvals.aria': 'Cordis تەستىقلىرى',
  'panel.trigger': 'Cordis Plugin',
  'panel.runningCount': '{count} running',
  'panel.title': 'Cordis قىستۇرمىلىرى',
  'panel.empty': 'تېخى ھېچقانداق قىستۇرما بېكىتىلمىدى',
  'panel.loading': 'ئوقۇلۇۋاتىدۇ…',
  'panel.readFailed': 'قىستۇرما تىزىملىكىنى ئوقۇش مەغلۇپ بولدى: {message}',
  'panel.group.current': 'بۇ سېئانس',
  'panel.group.others': 'باشقا سېئانسلار',
  'panel.version': 'نۇسخا',
  'panel.current': 'ھازىرقى: {packageId}',
  'panel.next': 'ئالماشتۇرۇلىدىغان: {packageId}',
  'action.approve': 'يول قويۇش',
  'action.approveOnce': 'پەقەت بۇ نۇسخىغا يول قويۇش',
  'action.approvePlugin': 'بۇ قىستۇرمىنىڭ كېيىنكى نۇسخىلىرىغا يول قويۇش',
  'action.decline': 'رەت قىلىش',
  'action.run': 'يۈرگۈزۈش',
  'action.stop': 'توختىتىش',
  'action.remove': 'چىقىرىۋېتىش',
  'action.retry': 'قايتا سىناش',
  'action.rollback': 'ئارقىغا قايتۇرۇش',
  'action.inspect': 'كۆرۈش',
  'render.failedAbdicated': '{slot} كۆرسىتىش مەغلۇپ بولدى، سۈكۈتتىكى ئارايۈز ئەسلىگە كەلتۈرۈلدى:',
  'render.failedHeld': '{slot} كۆرسىتىش مەغلۇپ بولدى:',
  'a11y.defining': 'قىستۇرما بېكىتىلىۋاتىدۇ',
  'a11y.failed': 'بېكىتىش مەغلۇپ بولدى',
  'a11y.stopped': 'بېكىتىش ئۈزۈلدى',
  'body.source': 'قىستۇرما كودى',
  'body.hostCode': 'Host',
  'body.clientCode': 'Client',
  'body.output': 'نەتىجە',
  'body.copy': 'كۆچۈرۈش',
  'body.copied': 'كۆچۈرۈلدى',
}
