var ugDeliverables = {
  'presented.nativeUnavailable': 'بۇ ھۆججەتنىڭ Host يولى يوق، يان بالداقتا ئالدىن كۆرۈڭ',
  'presented.revealError': 'ھۆججەت باشقۇرغۇچتا كۆرسىتەلمىدى، قايتا سىناڭ',
  'presented.directoryError': 'ئۆز ئىچىگە ئالغان ھۆججەت قىسقۇچىنى ئاچقىلى بولمىدى، قايتا سىناڭ',
  'presented.directoryOpening': 'ئۆز ئىچىگە ئالغان ھۆججەت قىسقۇچى ئېچىلىۋاتىدۇ…',
  'presented.directoryOpened': 'ئۆز ئىچىگە ئالغان ھۆججەت قىسقۇچىنى ئېچىش تەلەپ قىلىندى',
  'presented.revealed': 'ھۆججەت باشقۇرغۇچتا كۆرسىتىش تەلەپ قىلىندى',
  'presented.revealing': 'ھۆججەت باشقۇرغۇچتا كۆرسىتىلىۋاتىدۇ…',
  'presented.unavailable': 'بۇ Host تا ئىش ئۈستى يوق، ھۆججەت ياكى ھۆججەت قىسقۇچىنى ئاچقىلى بولمايدۇ',
  'presented.retry': 'قايتا سىناش',
  'presented.hostError': 'Host ئىش ئۈستى ئۇچۇرىنى ئوقۇيالمىدى',
  'presented.directory': 'ئۆز ئىچىگە ئالغان ھۆججەت قىسقۇچىنى ئېچىش',
  'presented.explorer': 'ھۆججەت تەكشۈرگۈچتە كۆرسىتىش',
  'presented.finder': 'Finder دا كۆرسىتىش',
  'presented.defaultApp': 'سۈكۈتتىكى پروگراممىدا ئېچىش',
  'presented.more': '{name} نىڭ تېخىمۇ كۆپ ھۆججەت مەشغۇلاتلىرى',
  'presented.action': 'ئېچىش',
  'presented.preview': 'يان بالداقتا ئالدىن كۆرۈش',
  'presented.previewButton': '{name} نى يان بالداقتا ئېچىش',
  'presented.previewCard': '{name} نى يان بالداقتا ئالدىن كۆرۈش',
  'presented.all': 'بارلىق {count} ھۆججەت',
  'presented.expandAria': 'بارلىق {count} تاپشۇرۇلغان ھۆججەتنى كۆرسىتىش',
  'presented.collapse': 'قاتلاش',
  'presented.collapseAria': 'تاپشۇرۇلغان ھۆججەتلەر تىزىمىنى قاتلاش',
  'presented.opening': 'ئېچىلىۋاتىدۇ…',
  'presented.opened': 'سۈكۈتتىكى پروگراممىدا ئېچىلدى',
  'presented.error': 'ئاچقىلى بولمىدى. قايتا سىناش ئۈچۈن چېكىڭ.',
  'presented.file': 'ھۆججەت',
  'row.title': 'تاپشۇرۇلغان ھۆججەتلەر',
  'row.running': 'تاپشۇرۇلۇۋاتىدۇ',
  'row.ok': 'تاپشۇرۇلدى',
  'row.error': 'تاپشۇرۇش مەغلۇپ بولدى',
  'row.stopped': 'ئۈزۈلدى',
  'row.inspect': 'چاقىرىشنى كۆرۈش',
  'presented.open': '{name} نى سۈكۈتتىكى پروگراممىدا ئېچىش',
  'produced.label': 'بۇ نۆۋەتتە ئۆزگەرگەن ھۆججەتلەر',
  'produced.moreOne': '+ 1 ھۆججەت',
  'produced.more': '+ {count} ھۆججەت',
  'produced.open': '{name} نى ئېچىش',
}
