var ugFeedback = {
  'action.like': 'ياخشى جاۋاب',
  'action.likeActive': 'بەلگىنى چىقىرىۋېتىش',
  'action.dislike': 'مەسىلىلىك جاۋاب',
  'action.dislikeActive': 'بەلگىنى چىقىرىۋېتىش',
  'dialog.title': 'پىكىر يوللاش',
  'dialog.categories': 'پىكىر تۈرى',
  'dialog.detail': 'پىكىر تەپسىلاتى',
  'dialog.hint': 'تەپسىلات تولدۇرۇپ تەجرىبىنى ياخشىلاشقا ياردەم قىلىڭ. يوللىغان مەزمۇنىڭىز ھازىرقى سۆھبەت جۇرنىلىنى ئۆز ئىچىگە ئالىدۇ.',
  'category.task-result': 'ۋەزىپە نەتىجىسى',
  'category.instruction-following': 'كۆرسەتمىنى چۈشىنىش ۋە ئەمەل قىلىش',
  'category.product-interaction': 'مەھسۇلات ئىقتىدارى ۋە ئارىلىشىش',
  'category.service-stability': 'مۇقىملىق ۋە سۈرئەت',
  'category.resource-cost': 'مەنبە ئىشلىتىش ۋە چىقىم',
  'category.security-privacy-permission': 'بىخەتەرلىك، شەخسىي مەخپىيەتلىك ۋە ھوقۇق',
  'category.other': 'باشقا',
  'toast.recorded': 'پىكرىڭىزگە رەھمەت',
  'error.conflict': 'بۇ پىكىر باشقا جايدا ئۆزگەرتىلىپتۇ، ئەڭ يېڭى ھالەت كۆرسىتىلدى',
  'error.load': 'پىكىر ھالىتىنى يۈكلىيەلمىدى',
  'error.generic': 'پىكىرنى ساقلىيالمىدى',
  'error.noteTooLarge': 'تەسۋىر بەك ئۇزۇن، قىسقارتىپ قايتا يوللاڭ',
}
