var ugJob = {
  'count.live.one': '{count} ئارقا پىلان ۋەزىپىسى ئىجرا بولۇۋاتىدۇ',
  'count.live.other': '{count} ئارقا پىلان ۋەزىپىسى ئىجرا بولۇۋاتىدۇ',
  'count.idle.one': '{count} ئارقا پىلان ۋەزىپىسى',
  'count.idle.other': '{count} ئارقا پىلان ۋەزىپىسى',
  'list.aria': 'ئارقا پىلان ۋەزىپىلىرى',
  'status.running': 'ئىجرا بولۇۋاتىدۇ',
  'status.stopping': 'توختىتىلىۋاتىدۇ',
  'status.completed': 'تاماملاندى',
  'status.killed': 'بىكار قىلىندى',
  'status.failed': 'مەغلۇپ بولدى',
  'duration.seconds': '{seconds} سېكۇنت',
  'duration.minutes': '{minutes} مىنۇت {seconds} سېكۇنت',
  'duration.hours': '{hours} سائەت {minutes} مىنۇت',
  'duration.title.live': 'ئىجرا بولغان ۋاقىت {duration}',
  'duration.title.done': 'سەرپ قىلىنغان ۋاقىت {duration}',
}
