var ugModel = {
  'command.description': 'بۇ سېئانستا ئىشلىتىدىغان مودېلنى تاللاش',
  'option.loadError': 'مۇندەرىجىنى يۈكلەش مەغلۇپ بولدى: {message}',
  'option.deepseekV4Flash.description': 'تېز، ئۈنۈملۈك ۋە تېجەشلىك؛ مەركەزلەشكەن، دائىملىق ياكى پاراللېل ۋەزىپىلەرگە ماس كېلىدۇ.',
  'option.deepseekV4Pro.description': 'تېخىمۇ كۈچلۈك ۋاكالەتچى كودلاش، بىلىم ۋە مۇرەككەپ خۇلاسە چىقىرىش؛ مۇرەككەپ ياكى سۈپەت ئەڭ مۇھىم بولغان ۋەزىپىلەرگە ماس كېلىدۇ، ئەمما تەننەرخى يۇقىرىراق.',
  'trigger.fallback': 'مودېل تاللاش',
  'trigger.loading': 'مودېللار يۈكلىنىۋاتىدۇ…',
  'trigger.selectAria': 'مودېل تاللاش',
  'trigger.aria': 'مودېل تاللاڭ، ھازىرقى {model}',
  'trigger.ariaEffort': 'مودېل تاللاڭ، ھازىرقى {model}، خۇلاسە چىقىرىش دەرىجىسى {effort}',
  'menu.aria': 'مودېل ۋە خۇلاسە چىقىرىش دەرىجىسى',
  'menu.model': 'مودېل',
  'menu.effort': 'خۇلاسە چىقىرىش دەرىجىسى',
  'effort.providerDefault': 'سۈكۈتتىكى',
  'status.loading': 'مودېل تىزىمى يېڭىلىنىۋاتىدۇ…',
  'error.action': 'مودېل مەشغۇلاتى مەغلۇپ بولدى: {message}',
  'action.reload': 'قايتا يۈكلەش',
  'warning.groupLoad': '{name} يۈكلەش مەغلۇپ بولدى: {message}',
  'empty.models': 'ئىشلەتكىلى بولىدىغان مودېل يوق.',
  'blocked.composer': 'ھازىرقى مودېل ئىشلەمەيدۇ — داۋاملاشتۇرۇش ئۈچۈن مودېل تاللاڭ',
  'empty.efforts': 'بۇ مودېل خۇلاسە چىقىرىش دەرىجىسىنى تەمىنلىمەيدۇ.',
}
