var ugQuestion = {
  'error.incomplete': 'ئاۋۋال بۇ سوئالنى تاماملاڭ.',
  'error.unanswered': 'بىر تاللانما تاللاڭ ياكى خاس جاۋاب يېزىڭ.',
  'nav.prev': 'ئالدىنقى سوئال',
  'nav.next': 'كېيىنكى سوئال',
  'nav.minimize': 'سوئال كارتىسىنى قاتلاش',
  'nav.maximize': 'سوئال كارتىسىنى يېيىش',
  'nav.cancel': 'پۈتۈن سوئال توپلىمىدىن ۋاز كېچىش',
  'option.recommended': 'تەۋسىيە',
  'custom.placeholder': 'جاۋابىڭىزنى يېزىڭ',
  'action.skip': 'بۇ سوئالنى ئاتلاپ ئۆتۈش',
  'action.next': 'كېيىنكى سوئال',
  'plan.header': 'پىلان تەكشۈرۈشنى كۈتۈۋاتىدۇ',
  'plan.approve': 'ئىجرانى تەستىقلاش',
  'plan.decline': 'رەت قىلىش',
  'plan.discuss': 'سۆھبەتتە مۇزاكىرە قىلىش',
}
