var ugScheduleCatalog = {
  'trigger.one': '{count} ئەسكەرتىش',
  'trigger.other': '{count} ئەسكەرتىش',
  'list.aria': 'ئاكتىپ ئەسكەرتىشلەر',
  'status.scheduled': 'كۈتۈلۈۋاتىدۇ',
  'status.overdue': 'ۋاقتى ئۆتۈپ كەتتى',
  'frequency.once': 'بىر قېتىم',
  'frequency.every': 'ھەر {value} {unit} دا بىر قېتىم',
  'unit.day.one': 'كۈن',
  'unit.day.other': 'كۈن',
  'unit.hour.one': 'سائەت',
  'unit.hour.other': 'سائەت',
  'unit.minute.one': 'مىنۇت',
  'unit.minute.other': 'مىنۇت',
  'unit.second.one': 'سېكۇنت',
  'unit.second.other': 'سېكۇنت',
  'relative.now': 'ھازىر ۋاقتى بولدى',
  'relative.future': '{value} {unit} دىن كېيىن',
  'relative.overdue': '{value} {unit} ۋاقتى ئۆتۈپ كەتتى',
}
