var ugSidebarRight = {
  'chrome.expand': 'يان بالداقنى ئېچىش',
  'chrome.expandAria': 'ئوڭ يان بالداقنى ئېچىش',
  'chrome.collapse': 'يان بالداقنى قاتلاش',
  'chrome.collapseAria': 'ئوڭ يان بالداقنى قاتلاش',
  'chrome.toFullscreen': 'تولۇق ئېكران',
  'chrome.exitFullscreen': 'تولۇق ئېكراندىن چىقىش',
  'dock.emptyPane': 'بوش تاختا',
  'dock.splitPane': 'بۆلۈش',
  'dock.splitPaneDisabled': 'ئىككى بۆلەك چەككە يەتتى',
  'dock.splitPaneNarrow': 'بالداق كەڭلىكى يېتەرلىك ئەمەس، بالداقنى كېڭەيتىپ ئاندىن بۆلۈڭ',
  'dock.closeTab': 'يېپىش',
  'dock.addTab': 'يېڭى بەتكۈچ',
  'dock.dockFloat': 'يان بالداققا قايتۇرۇش',
  'dock.closeFloat': 'يېپىش',
  'dock.drop.center': 'بۇ يەرگە يۆتكەش',
  'dock.drop.left': 'سول بۆلۈش',
  'dock.drop.right': 'ئوڭ بۆلۈش',
  'dock.drop.top': 'ئۈستى بۆلۈش',
  'dock.drop.bottom': 'ئاستى بۆلۈش',
  'tab.guide.title': 'باشلاش',
  'tab.unavailable': 'بۇ خىل مەزمۇننى كۆرۈش ئۇسۇلى تېخى يوق.',
}
