var ugSubagent = {
  'diagnostic.corrupt': 'سېئانس خاتىرىسى بۇزۇلغان',
  'diagnostic.unsupported': 'تارماق ۋاكالەتچى خاتىرىسىنىڭ نۇسخىسى قوللانمايدۇ',
  'diagnostic.unavailable': 'سېئانس خاتىرىسى ھازىرچە ئىشلەتكىلى بولمايدۇ',
  'duration.seconds': '{seconds} سېكۇنت',
  'duration.minutes': '{minutes} مىنۇت {seconds} سېكۇنت',
  'duration.hours': '{hours} سائەت {minutes} مىنۇت {seconds} سېكۇنت',
  'duration.days': '{days} كۈن',
  'duration.daysHours': '{days} كۈن {hours} سائەت',
  'duration.months': 'تەخمىنەن {months} ئاي',
  'duration.monthsDays': 'تەخمىنەن {months} ئاي {days} كۈن',
  'duration.years': 'تەخمىنەن {years} يىل',
  'duration.yearsMonths': 'تەخمىنەن {years} يىل {months} ئاي',
  'duration.exactDays': '{days} كۈن {hours} سائەت {minutes} مىنۇت {seconds} سېكۇنت',
  'duration.exactTitle': 'ئومۇمىي ئاكتىپ ۋاقىت: {duration}',
  'tokens.thousand': '{value}K',
  'tokens.million': '{value}M',
  'tokens.total': '{value} tok',
  'loading.label': 'تارماق ۋاكالەتچىلەر يۈكلىنىۋاتىدۇ…',
  'loading.aria': 'تارماق ۋاكالەتچىلەر يۈكلىنىۋاتىدۇ',
  'load.error': 'تارماق ۋاكالەتچىلەرنى يۈكلىيەلمىدى',
  'retry': 'قايتا سىناش',
  'mode.oneShot': 'بىر قېتىملىق',
  'mode.continuable': 'داۋاملاشقىلى بولىدىغان',
  'activity.running': 'ئىجرا بولۇۋاتىدۇ',
  'activity.inactive': 'ھازىر ئىجرا بولمايۋاتىدۇ',
  'branch.collapse': '{label} نىڭ تۆۋەنكى دەرىجىلىك تارماق ۋاكالەتچىلىرىنى قاتلاش',
  'branch.expand': '{label} نىڭ تۆۋەنكى دەرىجىلىك تارماق ۋاكالەتچىلىرىنى يېيىش',
  'count.total.one': '{count} تارماق ۋاكالەتچى',
  'count.total.other': '{count} تارماق ۋاكالەتچى',
  'count.running.one': '{count} تارماق ۋاكالەتچى ئىجرا بولۇۋاتىدۇ',
  'count.running.other': '{count} تارماق ۋاكالەتچى ئىجرا بولۇۋاتىدۇ',
  'switcher.aria': 'تارماق ۋاكالەتچىنى ئالماشتۇرۇش: {title}',
  'tree.aria': 'تارماق ۋاكالەتچى سېئانلىرى',
  'readonly.oneShot.title': 'بىر قېتىملىق تارماق ۋاكالەتچى خاتىرىسى',
  'readonly.title': 'بۇ تارماق ۋاكالەتچى ھازىرچە پەقەت ئوقۇشقا بولىدۇ',
  'readonly.oneShot.body': 'بىر قېتىملىق ۋەزىپىلەر كېيىنكى ئۇچۇرلارنى قوبۇل قىلمايدۇ؛ تولۇق ئىجرا خاتىرىسىنى بۇ يەردە كۆرەلەيسىز.',
  'readonly.body': 'ئانا سېئانس ھازىر تورسىز؛ ئۇنى قايتا ئاچقاندىن كېيىن ئۇچۇر ئەۋەتىشنى داۋاملاشتۇرالايسىز.',
}
