var ugWorkspace = {
  'group.ungrouped': 'گۇرۇپپىسىز',
  'session.new': 'يېڭى سېئانس',
  'section.workspaces': 'خىزمەت بوشلۇقلىرى',
  'section.sessions': 'سېئانسلار',
  'viewOptions.label': 'كۆرۈنۈش تاللانمىلىرى',
  'groupBy.label': 'گۇرۇپپىلاش ئۇسۇلى',
  'groupBy.workspace': 'خىزمەت بوشلۇقى بويىچە',
  'groupBy.flat': 'بىر تىزما',
  'orderBy.label': 'تەرتىپلەش ئۇسۇلى',
  'orderBy.manual': 'قولدا تەرتىپلەش',
  'orderBy.updated': 'ئەڭ يېقىن يېڭىلانغان',
  'sessions.expand': 'قالغان {n} سېئانسنى كۆرسەت',
  'sessions.collapse': 'ئاز كۆرسىتىش',
  'empty.none': 'تېخى سېئانس يوق',
  'empty.noMatches': 'ماس كېلىدىغان نەتىجە يوق',
  'workspace.add': 'خىزمەت بوشلۇقى قوشۇش',
  'search.sessions.aria': 'سېئانسلارنى ئىزدەش',
  'search.placeholder': 'سېئانسلارنى ئىزدەش…',
  'search.clear': 'ئىزدەشنى تازىلاش',
  'search.results.aria': 'ئىزدەش نەتىجىسى',
  'search.pending': 'سېئانس تارىخى ئىزدىلىۋاتىدۇ…',
  'search.unavailable': 'مەزمۇن ئىزدەش ھازىرچە ئىشلىمەيدۇ. پەقەت ئىسىم ماسلىقى كۆرسىتىلىدۇ.',
  'search.noMatches': 'ماس كېلىدىغان سېئانس يوق',
  'search.hasMore': 'پەقەت ئالدىنقى {n} نەتىجە كۆرسىتىلدى. ئىزدەش دائىرىسىنى تارايتىڭ.',
  'menu.addWorkspace': 'خىزمەت بوشلۇقى قوشۇش…',
  'picker.loading': 'خىزمەت بوشلۇقلىرى يۈكلىنىۋاتىدۇ…',
  'conflict.named': '«{name}» دېگەن خىزمەت بوشلۇقى ئاللىقاچان مەۋجۇت.',
  'folderError.title': 'ھۆججەت قىسقۇچىنى ئاچقىلى بولمىدى',
  'folderError.retry': 'قايتا تاللاش',
  'rename': 'ئاتىنى ئۆزگەرتىش',
  'rename.workspace.title': 'خىزمەت بوشلۇقىنىڭ ئاتىنى ئۆزگەرتىش',
  'rename.session.title': 'سېئانسنىڭ ئاتىنى ئۆزگەرتىش',
  'field.workspaceName': 'خىزمەت بوشلۇقى ئاتى',
  'field.sessionName': 'سېئانس ئاتى',
  'delete.workspace': 'خىزمەت بوشلۇقىنى ئۆچۈرۈش',
  'delete.desc': '«{name}» خىزمەت بوشلۇقى تىزىمىدىن چىقىرىۋېتىلىدۇ. ھۆججەت قىسقۇچى ۋە سېئانس جۇرناللىرى ساقلىنىدۇ. ئۇنىڭ سېئانلىرى «گۇرۇپپىسىز» دا كۆرۈنىدۇ.',
  'delete.pending': 'خىزمەت بوشلۇقى ئۆچۈرۈلۈۋاتىدۇ…',
  'menu.fork': 'سېئانسنى ئايرىش',
  'menu.archiveSession': 'سېئانسنى ئارخىپلاش',
  'sessions.count.one': '{n} سېئانس',
  'sessions.count.other': '{n} سېئانس',
  'actions.workspace.aria': '«{name}» خىزمەت بوشلۇقىنىڭ مەشغۇلاتلىرى',
  'actions.session.aria': '«{name}» سېئانسىنىڭ مەشغۇلاتلىرى',
  'actions.newSession.aria': '«{name}» دا يېڭى سېئانس قۇرۇش',
  'status.running': 'داۋاملاشماقتا',
  'status.subagentsRunning.one': '{n} تارماق ۋاكالەتچى ئىجرا بولۇۋاتىدۇ',
  'status.subagentsRunning.other': '{n} تارماق ۋاكالەتچى ئىجرا بولۇۋاتىدۇ',
  'status.idle': 'بىكار',
  'status.waitingApproval': 'تەستىقنى كۈتۈۋاتىدۇ',
  'status.planReview': 'پىلان تەكشۈرۈشنى كۈتۈۋاتىدۇ',
  'status.waitingAnswer': 'جاۋاب كۈتۈۋاتىدۇ',
  'status.completed': 'تاماملاندى',
  'schedule.active': 'ئاكتىپ ۋاقىتلىق ۋەزىپە بار',
  'hover.created': '{time} دا قۇرۇلدى',
  'hover.copied': 'كۆچۈرۈلدى',
  'date.ymd': '{y}-يىل {m}-ئاي {d}-كۈن',
  'time.now': 'ھازىرلا',
  'time.minutes': '{n} مىنۇت',
  'time.hours': '{n} سائەت',
  'time.days': '{n} كۈن',
  'time.months': '{n} ئاي',
  'time.years': '{n} يىل',
  'time.ago': '{t} ئىلگىرى',
}
