var ugWorkflowRun = {
  'run.title': '{name}',
  'run.members.one': '{count} ئەزا',
  'run.members.other': '{count} ئەزا',
  'run.empty': 'ئەزا قوزغىتىلمىدى',
  'phase.unassigned': 'باسقۇچسىز',
  'phase.empty': 'بوش باسقۇچ ئاتى',
  'statusCount.running': 'ئىجرا بولۇۋاتىدۇ {count}',
  'statusCount.completed': 'تاماملاندى {count}',
  'statusCount.failed': 'مەغلۇپ بولدى {count}',
  'statusCount.cancelled': 'بىكار قىلىندى {count}',
  'statusCount.interrupted': 'ئۈزۈلدى {count}',
  'member.empty': 'بوش ئەزا ئاتى',
  'member.open': '{name} نى ئېچىش',
  'status.running': 'ئىجرا بولۇۋاتىدۇ',
  'status.completed': 'تاماملاندى',
  'status.failed': 'مەغلۇپ بولدى',
  'status.cancelled': 'بىكار قىلىندى',
  'status.interrupted': 'ئۈزۈلدى',
}
